### ISSUE TITLE
std-issue 01

### ISSUE THREAD

**Issue by zsimon01** [zsimon01/zsrepo#1]
My PC had overheat issue, when I connected it to a Servo Motor, through an Arduino Board.
The conditions were:
- it was running from battery;
- ...

However I am sure, my good frends:
@GithubLarion1998 ,and
@zsolt890828 ,and
@imre-berente will have ideas to resolve this problem.
Yes, I agree with Imre, and I am using the power supply. Thanks for your feedback.

**Comment by imre-berente** [comment]
When servo (or anything) is powered from a PC, the PC needs to generate
this power, putting more load to its power supply or battery. If those
can't take this extra load, they overheat. Use the provided external power
source that can be plugged into a phone charger
